### ISSUE TITLE
Lambda Function URL support missing in v1.1.0 package on NPM.

### ISSUE THREAD

**Issue by gotgenes** [wingleung/remix-aws#35]
Despite #9, the v1.1.0 package on NPM does not actually contain the enum value `AWSProxy.FunctionURL`, nor the code to handle it in `createRemixAdapter`. This can be seen on [NPM's code display](https://www.npmjs.com/package/remix-aws?activeTab=code).

**Comment by wingleung** [comment]
@gotgenes 🙏 thanks for letting me know, when I published a new beta version the `AWSProxy.FunctionURL` did get added now, sorry for the delay

**Comment by wingleung** [comment]
📢 released in version [1.2.2](https://www.npmjs.com/package/remix-aws/v/1.2.2)
