### ISSUE TITLE
Unhandled errors on invalid requests

### ISSUE THREAD

**Issue by brettdh** [wingleung/remix-aws#44]
I've seen two errors in my logs when the request data is invalid (usually from scanner traffic). Both are in [`createRemixRequest`](https://github.com/wingleung/remix-aws/blob/6186f517ca4fe56e627377c84e07376529bc9985/src/adapters/api-gateway-v2.ts#L13-L33); I'm using the API Gateway v2 adapter, but I think this applies to other adapters too.

Examples of invalid requests:
1. A GET or HEAD request with a body (`new Request` throws)
2. An invalid URL like `https://foo\"><script>alert(document.domain)</script><x=\".com` (`new URL` throws)

In both cases, we get an uncaught exception; it would be better to catch these errors and return a 400 status code indicating the request was malformed.

**Comment by wingleung** [comment]
that makes more elegant indeed ❤️  PR created with your fix
I do recommend also checking if you could block this earlier on in the request chain, for example using a WAF with specific rules or narrowing your api gateway settings. Either way people will still be able to send bad requests, thanks for the improvement! 🙏

**Comment by brettdh** [comment]
Thanks for the tip. 🙂 Setting up a WAF is definitely on our todo list.

**Comment by wingleung** [comment]
📢 published in beta version [1.2.0-beta.3](https://www.npmjs.com/package/remix-aws/v/1.2.0-beta.3)

**Comment by wingleung** [comment]
📢 released in version [1.2.2](https://www.npmjs.com/package/remix-aws/v/1.2.2)
