### ISSUE TITLE
Add Lambda URL support

### ISSUE THREAD

**Issue by moltar** [wingleung/remix-aws#9]
I think having an explicit enum option mapping to APIG v2 value would be good for DX.

Docs:

- https://docs.aws.amazon.com/lambda/latest/dg/lambda-urls.html
- https://docs.aws.amazon.com/lambda/latest/dg/urls-invocation.html#urls-payloads

> The request and response event formats follow the same schema as the [Amazon API Gateway payload format version 2.0](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-lambda.html#http-api-develop-integrations-lambda.proxy-format).

**Comment by wingleung** [comment]
would be more verbose idd, 👍

**Comment by wingleung** [comment]
added in https://github.com/wingleung/remix-aws/releases/tag/v1.1.0
